.TH ghzen 7

.SH NAME
ghzen \- displays one of The Zen of GitHub (https://api.github.com/zen)

.SH SYNOPSIS
\fBghzen\fP [--all] [--help] [--version]

.SH DESCRIPTION
Displays one of the phrases from The Zen of GitHub

\fB-a\fR, \fB--all\fR
      displays all phrases

\fB-h\fR, \fB--help\fR
      displays a help message

\fB-v\fR, \fB--version\fR
      displays the version number

.SH BUGS
https://github.com/tallesl/ghzen/issues

.SH AUTHOR
Talles L <talleslasmar@gmail.com>
