.TH ghzen 7

.SH NAME
ghzen \- prints one of The Zen of GitHub

.SH SYNOPSIS
\fBghzen\fP

.SH DESCRIPTION
Randomly picks one of the phrases from The Zen of GitHub and prints to stdout.

\fB-h\fR, \fB--help\fR
      displays a help message and exit

\fB-v\fR, \fB--version\fR
      displays the version number and exit

.SH BUGS
https://github.com/tallesl/ghzen/issues

.SH AUTHOR
Talles L <talleslasmar@gmail.com>

